### PR TITLE
Remove ANGLER_DATA from global namespace

### PR DESCRIPTION
**Pull request by cloudbells**
Should double check to see that nothing is broken.

### CODE REVIEW

**Comment by Deahgib** [comment]
I see you are using:
local _, ns = ...
ns.ANGLER_DATA 

I'm new to wow addon dev. 
Firstly there has been a number of project refactors and now ANGLER_DATA is called AnglerAtlas.
AnglerAtlas is my data source but also my source to build my app to between files to maintain cross file contexts. 
What's the best practice here in your opinion. The AnglerAtlas table does contain data that could be read and processed by anyone. Personally I thought making it global would be good practice to give anyone access to my compiled data.

**Comment by cloudbells** [comment]
Aside from a minor performance increase (negligible) it's a good idea to generally not pollute the global namespace.

If you want to expose some data or some operations on your data, it would be better to not expose the raw table but instead provide APIs for that. That makes it cleaner and easier to work with.

**Comment by Deahgib** [comment]
That makes sense. I would love to understand the slight performance increase. 
I don't need to expose any data I guess. I just wanted to allow devs to have the data if someone ever needed it. 
In principle however I agree with not polluting the global namespace so I'll make sure to create a namespace and a global api.
Just to confirm
Do I use this at the top of all my files that reference my AnglerAtlas table? And what is this instruction:  local _, ns= ... 
local _, AANamespace = ...
AANamespace.AnglerAtlas

**Comment by cloudbells** [comment]
You bypass looking stuff up in the global table. So essentially behind the scenes instead of going _G["AnglerData"]["yourDataPoint"] it can simply do ns["yourDataPoint"].

When each Lua file gets loaded it gets sent two things: your addon name as well as a table allocated for your addon. Every file you declare in your .toc gets injected with this table. It's meant as a way to share variables and functions between files. This data is accessed using the ellipsis (...). You can obviously rename this variable to whatever you want. The underscore is just used to discard the first argument.

**Comment by cloudbells** [comment]
Oops, never mind my comment about the performance increase! :)

**Pull request closed without merging**
